export const fontOptions = [
    { display: "Arial", value: "Arial, sans-serif" },
    { display: "Helvetica", value: "Helvetica, sans-serif" },
    { display: "Verdana", value: "Verdana, sans-serif" },
    { display: "Georgia", value: "Georgia, serif" },
    { display: "Times New Roman", value: "Times New Roman, serif" },
    { display: "Courier New", value: "Courier New, monospace" },
    { display: "Trebuchet MS", value: "Trebuchet MS, sans-serif" },
    { display: "Century Gothic", value: "Century Gothic, sans-serif" },
    { display: "Garamond", value: "Garamond, serif" },
    { display: "Palatino Linotype", value: "Palatino Linotype, serif" },
    { display: "Lucida Sans Unicode", value: "Lucida Sans Unicode, sans-serif" },
    { display: "Tahoma", value: "Tahoma, sans-serif" },
    { display: "Impact", value: "Impact, sans-serif" },
    { display: "Book Antiqua", value: "Book Antiqua, serif" },
    { display: "Arial Black", value: "Arial Black, sans-serif" },
    { display: "Comic Sans MS", value: "Comic Sans MS, sans-serif" },
    { display: "Franklin Gothic Medium", value: "Franklin Gothic Medium, sans-serif" },
    { display: "Rockwell", value: "Rockwell, serif" },
    { display: "Candara", value: "Candara, sans-serif" },
    { display: "Consolas", value: "Consolas, monospace" },
];